### PR TITLE
Finish up the app for the release

### LINKED ISSUE #1: Update feed URL to nextcloud only
https://github.com/nextcloud/nextcloud_announcements/blob/master/lib/Cron/Crawler.php#L37

### LINKED ISSUE #2: Last modified header of feed is not checked
Contribook does not support it
https://github.com/nextcloud/nextcloud_announcements/blob/master/lib/Cron/Crawler.php#L82-L87

### LINKED ISSUE #10: Icon please
@jancborchardt

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1 
Fix #2 
Fix #10 

> bildschirmfoto vom 2016-11-18 14-46-52

Feed generation is in https://github.com/nextcloud/announcer

### CODE REVIEW

**Comment by nickvergessen** [comment]
@LukasReschke @MorrisJobke 

Feed generation is in https://github.com/nextcloud/announcer

**Comment by MorrisJobke** [comment]
👍  🙈

**Comment by jancborchardt** [comment]
Was just thinking that the actual Nextcloud logo might be better as icon … because this is only for announcements from us, right?

**Comment by nickvergessen** [comment]
yes

**Pull request merged**
